DROP DATABASE IF EXISTS employeetracker_db;

CREATE DATABASE employeetracker_db;

USE employeetracker_db;

CREATE TABLE  employees(
    id INT AUTO_INCREMENT PRIMARY KEY,            
    FIRST_NAME VARCHAR(30) NOT NULL,  
           LAST_NAME  VARCHAR(30) NOT NULL,
           ROLE_ID    INT(10) NOT NULL,
           MANAGER_ID INT(10)
);

   CREATE TABLE ROLES(
  
  id INT AUTO_INCREMENT PRIMARY KEY,
  EMPOLYEE_TITLE       VARCHAR(30) NOT NULL,
  EMPOLYEE_PAY_SALARY  DECIMAL NOT NULL,
  DEP_ID            INT (10)
  );
  
  CREATE TABLE department (
	 id INT AUTO_INCREMENT PRIMARY KEY,
     name VARCHAR(30) UNIQUE NOT NULL
  );
